exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('patients')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('patients').insert([
        {
          id: 1,
          name: 'Diego Santana',
          email: 'pessoa1@pessoa1.com',
          password: 'pessoa1',
          age: 25,
          city: 'Mafra',
          bloodType: 'AB',
          weight: 73,
          height: 1.7,
          problem: 'love Java',
          historic: 'https://www.google.com/',
        },
        {
          id: 2,
          name: 'Joanderson santos',
          email: 'pessoa2@pessoa2.com',
          password: 'pessoa2',
          age: 19,
          city: 'Candeias',
          bloodType: 'O',
          weight: 60,
          height: 1.7,
          problem: 'anemia',
          historic: 'https://www.google.com/',
        },
        {
          id: 3,
          name: 'Jefferson Eloy',
          email: 'pessoa3@pessoa3.com',
          password: 'pessoa3',
          age: 19,
          city: 'Candeias',
          bloodType: 'A',
          weight: 60,
          height: 1.8,
          problem: 'febre',
          historic: 'https://www.google.com/',
        },
        {
          id: 4,
          name: 'Guilherme Caires',
          email: 'pessoa4@pessoa4.com',
          password: 'pessoa4',
          age: 19,
          city: 'Madre de Deus',
          bloodType: 'B',
          weight: 58,
          height: 1.8,
          problem: 'febre',
          historic: 'https://www.google.com/',
        },
        {
          id: 5,
          name: 'João dos Santos',
          email: 'pessoa5@pessoa5.com',
          password: 'pessoa5',
          age: 17,
          city: 'Camaçari',
          bloodType: 'O',
          weight: 70,
          height: 1.75,
          problem: 'diabetes tipo 1',
          historic: 'https://www.google.com/',
        },
        {
          id: 6,
          name: 'Jennifer Brito',
          email: 'pessoa6@pessoa6.com',
          password: 'pessoa6',
          age: 16,
          city: 'Camaçari',
          bloodType: 'A',
          weight: 67,
          height: 1.65,
          problem: 'diabetes tipo 2',
          historic: 'https://www.google.com/',
        },
        {
          id: 7,
          name: 'Douglas Santana',
          email: 'pessoa7@pessoa7.com',
          password: 'pessoa7',
          age: 25,
          city: 'São Francisco do Conde',
          bloodType: 'A',
          weight: 70,
          height: 1.8,
          problem: 'anemia',
          historic: 'https://www.google.com/',
        },
        {
          id: 8,
          name: 'Loxt',
          email: 'pessoa8@pessoa8.com',
          password: 'pessoa8',
          age: 16,
          city: 'Candeias',
          bloodType: 'AB',
          weight: 65,
          height: 1.78,
          problem: 'do not like vscode',
          historic: 'https://www.google.com/',
        },
        {
          id: 9,
          name: 'Bianca santos',
          email: 'pessoa9@pessoa9.com',
          password: 'pessoa9',
          age: 23,
          city: 'São Francisco do Conde',
          bloodType: 'AB',
          weight: 68,
          height: 1.78,
          problem: 'anemia',
          historic: 'https://www.google.com/',
        },
        {
          id: 10,
          name: 'Fernanda',
          email: 'pessoa1@pessoa1.com',
          password: 'pessoa1',
          age: 16,
          city: 'Candeias',
          bloodType: 'AB',
          weight: 75,
          height: 1.79,
          problem: 'diabetes tipo 1',
          historic: 'https://www.google.com/',
        },
      ]);
    });
};
