exports.seed = (knex) => {
  // Deletes ALL existing entries
  return knex('doctors')
    .del()
    .then(() => {
      // Inserts seed entries
      return knex('doctors').insert([
        {
          id: 1,
          name: 'Fernando Albuquerque',
          uf: 'BA',
          municipality: 'Candeias',
          crm: '00000000',
          subscriptionType: 'Principal',
          speciality: 'Hepatologia',
          situation: 'Ativo',
          actuationArea: 'Dor',
        },
        {
          id: 2,
          name: 'Iago Santana',
          uf: 'BA',
          municipality: 'Camaçari',
          crm: '00000000',
          subscriptionType: 'Secundaria',
          speciality: 'Cirurgia digestiva',
          situation: 'Inativo',
          actuationArea: 'Perícia medica',
        },
        {
          id: 3,
          name: 'Thais Gusmão',
          uf: 'RJ',
          municipality: 'Candeias',
          crm: '00000000',
          subscriptionType: 'Principal',
          speciality: 'Acupuntura',
          situation: 'Ativo',
          actuationArea: 'Dor',
        },
        {
          id: 4,
          name: 'Beatriz dos santos',
          uf: 'SP',
          municipality: 'Araçás',
          crm: '00000000',
          subscriptionType: 'Provisoria',
          speciality: 'Hepatologia',
          situation: 'Inativo',
          actuationArea: 'Perícia medica',
        },
        {
          id: 5,
          name: 'Yasmin Santana',
          uf: 'SC',
          municipality: 'Araci',
          crm: '00000000',
          subscriptionType: 'Provisoria',
          speciality: 'Hepatologia',
          situation: 'Ativo',
          actuationArea: 'Dor',
        },
        {
          id: 6,
          name: 'Emmely Lima',
          uf: 'MT',
          municipality: 'Araçoiaba',
          crm: '00000000',
          subscriptionType: 'Provisoria',
          speciality: 'Cirurgia digestiva',
          situation: 'Inativo',
          actuationArea: 'Administração em Saúde',
        },
        {
          id: 7,
          name: 'Sandryelle Borges',
          uf: 'DF',
          municipality: 'Araçoiaba',
          crm: '00000000',
          subscriptionType: 'Secundaria',
          speciality: 'Hepatologia',
          situation: 'Ativo',
          actuationArea: 'Dor',
        },
        {
          id: 8,
          name: 'Fernando Lima',
          uf: 'BA',
          municipality: 'Araçatuba',
          crm: '00000000',
          subscriptionType: 'Principal',
          speciality: 'Angiologia',
          situation: 'Inativo',
          actuationArea: 'Administração em Saúde',
        },
        {
          id: 9,
          name: 'Diego Santana',
          uf: 'MT',
          municipality: 'Camaçari',
          crm: '00000000',
          subscriptionType: 'Secundaria',
          speciality: 'Hepatologia',
          situation: 'Inativo',
          actuationArea: 'Administração em Saúde',
        },
        {
          id: 10,
          name: 'Jessica Santos',
          uf: 'MT',
          municipality: 'Araçatuba',
          crm: '00000000',
          subscriptionType: 'Principal',
          speciality: 'Angiologia',
          situation: 'Ativo',
          actuationArea: 'Dor',
        },
      ]);
    });
};
